apiVersion: ENC[AES256_GCM,data:clE=,iv:CbbnIkggYgiR9yu2dYhlhJ837CDx8xqqu1WmTJH+Oa8=,tag:y4bL2XWcLH9E1jEM0SmLZw==,type:str]
kind: ENC[AES256_GCM,data:U4MKw01e,iv:EraUKtY2T+uTSrqm4/LqOSUI7OVCcEnDrxtgk8PPxo0=,tag:ErpvIGNM0qlP0LlCKQhk6w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8NJ3Ay2VgUU=,iv:jWtK4GrTGDBbZNS7XZ9sv56+e7fLnfsNs2/27g65glE=,tag:Ca1IVLwxlwopXdpzbKqO4Q==,type:str]
type: ENC[AES256_GCM,data:Sa53q75f,iv:yJXHGHsJ9qhIqzNVtjlIBDQjaCht61T6RX6TapJLxsI=,tag:4U9mczdGKgPU8ZSubyG8xQ==,type:str]
data:
    username: ENC[AES256_GCM,data:60T6+YY6u9o=,iv:OFrnxiCtDAC6c64j0Ka73jNB9jCV6OODkX3oq9gy3Mg=,tag:yWJJwtpV5+HWeKS2pDpmNw==,type:str]
    password: ENC[AES256_GCM,data:O/5P1w3a4P8YrPUjRW4JyQ==,iv:hO4JvRzQN43/KfcyXXQlBXKU0nzUpk/PhM1JHn1gNKc=,tag:l8yJCfgZVzMzjDq+lSWcEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v34shlqv52vggpp54e3fn93rna2wek84s40lkv6wlzjun5xm6ekqemjhn3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTFEwdEpqSDZSQTlqQk90
            UW9vSjV3RW5YcXRIWGFmZjA4eTRpYlVhWnpBCjZoamhGV2J5Wlhlb3EvdmRPUlpE
            YXJsbkRzSVhVeUFkQ3Fvc0g2cnQ5SWMKLS0tIFhDN1hveTFiWDB1elFuK2Z5MjNh
            MGJMRFA5eG8zVFJFT0kwY0UxNjVVejAKmGbPcMpouLeVidawoWzBO8vTld9vgb8r
            V0OMHcyWWWeFKmydWSV38X6rag1jLr3gRYBhc1dCysvAZ2KbTghpZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-07T09:04:27Z"
    mac: ENC[AES256_GCM,data:PHxL3Or113MAPU50P0lavgYINYNO9Y3fbuzY/GK62UJznmNsDy6ZS2yXYOI/AKbRkJBcqrwU2fqvYIZgPZzoKKHz6grQjdOan9FbdbaM6Y9JKkyQvyFqPisWRqW+ZpoMhi+pHrtuvPd4sTnIuzG+Oc0FdFfc1TOzomfSH1733oM=,iv:d4KRLgIDAYqJvjeCF7pkDQ23jM+kMbWQ4QLZDT1XcvM=,tag:UOIqs4y00ljN1G9xvqEWlQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
